"""empty message

Revision ID: a60806379148
Revises: 6c649fd0bc03
Create Date: 2022-08-28 22:41:48.009994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60806379148'
down_revision = '6c649fd0bc03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('browser_version', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('device_family', sa.String(), nullable=True),
    sa.Column('device_brand', sa.String(), nullable=True),
    sa.Column('device_model', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('refresh_tokens',
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('auth_token', sa.String(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('refresh_token'),
    sa.UniqueConstraint('auth_token')
    )
    op.create_unique_constraint(None, 'employees', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_table('refresh_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
